[build]
  command = "node generate.js"
  publish = "public"

[[redirects]]
  from = "/"
  to = "/start.json"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "*"
    Content-Type = "application/json; charset=utf-8"

[[headers]]
  for = "/"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "*"
    Content-Type = "application/json; charset=utf-8"
